### ISSUE TITLE
iProtector conflinct

### ISSUE THREAD

**Issue by NycuRO** [jjplaying/Worlds#10]
If you use iProtector plugin ,area pos1 pos2 with god flag not work on plugin..

You can fix? I need area pos1 pos2 god.. for spawn

**Comment by jjplaying** [comment]
Do you mean that I shouldn't use those commands because they're already used by iProtector?

**Comment by NycuRO** [comment]
Yes. I need to disable pvp in my island ( SkyPvP ) and in other enable. For this i need pos1 pos2 ..

**Comment by jjplaying** [comment]
So this is a duplicate of #9.

**Comment by jarne** [comment]
Now I unterstand your issue, it has been fixed with #15.

**Comment by NycuRO** [comment]
wow, nov 2016.....

**Comment by jarne** [comment]
Sorry, I didn't worked on those plugins for a few months because I were busy with other things.
